### PR TITLE
various usability updates

### PR DESCRIPTION
**Pull request by danomatika**
Howdy,

I made some updates for a project I'm, working on:
- **added a codeblocks project for the example:** I had to add a define check for UINT64_C as it was missing in gcc for some reason. See [here](http://code.google.com/p/ffmpegsource/issues/detail?id=11) for details. You should probably double check there isn't a clash with the define in VS.
- **updated the gitignore**
- **added the ability to set the file prefix and folder path to the record function**
- **added setRecordingArea:** to allow for usage beyond recording the normal screen. This should work with FBOs as well.
- **added setPixelSource:** to allow for recording an external source (ofImage, FBO, etc) instead of the screen

### CODE REVIEW

**Comment by danomatika** [comment]
Woops. Sorry about the line spaces etc. I forgot to turn off the auto whitespace formatter in CodeBlocks.

**Comment by danomatika** [comment]
I also updated my code formatting to match yours.

**Comment by danomatika** [comment]
2 more small changes:
- Your usage of ofLogError was incorrect. The first string is the log topic, not the log message. This is fixed by using ofLog(OF_LOG_ERROR ....
- I added the close true bool to stopThread() so it exits more quickly as my app was hanging on exit waiting for the recording thread.

**Comment by neilmendoza** [comment]
Thanks for the updates.  Had assume that ofLogError("blah") was a wrapper for ofLog(OF_LOG_ERROR, "blah") but I guess not...

**Comment by danomatika** [comment]
It is, just with a stream interface.

**Pull request merged**
